labels = {
    'errors': {
      'db_connection': "код ошибки: {0}",
      'db_request': "код ошибки: {0}",
      'empty_list': "На этой странице ещё не добавлена информация",
      'empty_jury': "Чтобы добавить члена жюри, нажмите на кнопку справа снизу",
      'empty_topics': "Чтобы начать добавлять темы, нажмите на кнопку справа снизу",
      'empty_groups': "Как только первая группа зарегистрируется, здесь появится карточка с информацией о ней",
    },
    'elements': {
        'participants_panel_title': "Список группы",
        'add_topic_btn': "Добавить новую тему",
        'no_data': "Данные отсутствуют",
        'bot_link': "https://t.me/bot_name?start=jury_{0}",
        'loading': "Загружаем",
        'app_version': "сборка {0}",
        'db_error_title': "Ошибка БД",
        'marks_title': "Оценки",
        'no_marks_subtitle': "не выставлены",
        'part_list': "Состав группы",
        'edit_topic_title': "Редактирование темы",
        'edit_params_title': "Изменение параметра"
    },
    'buttons': {
        'delete': "Удалить",
        'save': "Сохранить",
        'edit': "Изменить",
        'link': "Ссылка",
        'add': "Добавить",
        'check': "Проверить",
        'checking': "Проверяем",
        'accept': "Подтвердить",
        'group_info': "Информация о группе",
        'login': "Войти",
        'update_project': "Обновить проект",
        'copy_error_text': "Скопировать текст ошибки",
        'copy': "Копировать",
        'copy_code': "Копировать код",
        'video_link': "Открыть видео",
        'group_part': "Участники",
        'upload': "Открыть форму",
        'edit_token': "Изменить токен",
        'edit_password': "Изменит пароль"
    },
    'fields': {
        'login': "Логин",
        'password': "Пароль",
        'topic_description': "Название",
        'confirm_code': "Код подтверждения",
        'jury': "ФИО",
        'new_topic': "Тема"

    },
    'fields_hint': {
        'param': 'Введите значение параметра',
        'topic_description': "Введите название темы",
        'confirm_code': "Введите код подтверждения",
        'jury': "Иванов Иван Иванович",
        'new_topic': "Введите описание темы"
    },
    'snack_bars': {
        'welcome': "С возвращением!",
        'wrong_login': "Неверный логин или пароль",
        'link_copied': "Пригласительная ссылка скопирована",
        'error_text_copied': "Текст ошибки скопирован",
        'action_unavaliable': "Действие недоступно",
        'group_list_copied': "Состав группы скопирован",
        'element_deleted': "Элемент удалён",
        'table_deleted': "Таблица удалена",
        'data_edited': "Данные изменены",
        'data_updated': "Данные обновлены",
        'loading': "Загружаем",
        'accesscode_copied': "Код подключения скопирован",
        'topic_added': "Тема добавлена"
    },
    'titles': {
        'removing_data': "Удаление данных",
        'auth': "Авторизация",
        'single_add': "Одиночное добавление",
        'multi_add': "Массовое добавление",
        'confirm_action': "Подтверждение действия",
        'topics': "Темы",
        'groups': "Группы",
        'jury': "Жюри",
    },
    'statuses': {
        'topic_free': "Свободна",
        'topic_busy': "Занята",
        'jury_waiting': "Ожидание",
        'jury_registered': "Зарегистрирован",
        'video_waiting': "Открыть видео",
        'video_uploaded': "Открыть видео",
        'oauth_token': "OAuth-токен",
        'bot_token': "Bot-токен",
        'password': "Пароль"
    },
    'simple_text': {
        'upload_topics': "Скопируйте код подключения, после чего откройте форму и вставьте список тем, не забудьте вставить скопированный код подключения",
        'confirm_action': "Чтобы подтвердить своё действие, введите в окно {0}",
        'bot_token_descr': "Токен для связи с Telegram API",
        'oauth_token_descr': "Токен для связи бота с Яндекс.Диском",
        'password_descr': "Пароль для входа в панель управления и подтверждения действий",
        'rem_topics_descr': "Удаляются все темы, которые находятся в базе данных",
        'rem_groups_descr': "Удаляются все участники, загруженные видео, очищается список групп, в том числе рейтинг",
        'rem_jury_descr': "Удаляется всё жюри с потерей доступа к оцениваю работ",
    },
    'error_titles': {
        'empty_list': "Ничего не осталось",
        'no_jury': "Никого не видим",
        'no_topics': "Не нашли ни одной темы",
        'no_groups': "Ждём первую группу",
        'db_connect': "Ошибка базы данных",
        'db_request': "Ошибка базы данных",
    }
}